### PR TITLE
remove dynamic gas model

### PR DESCRIPTION
**Pull request by godsflaw**
The PR removes:
- the dynamic gas model from all model files
- the dynamic gas library
- all of the environment variables related to the dynamic gas model
- all the README references to the dynamic gas model

### CODE REVIEW

**Review by grandizzy — CHANGES_REQUESTED** [review]
we should also remove https://github.com/makerdao/dockerized-auction-keeper/blob/master/flip/bat-a/flip-bat-a.sh#L5 and https://github.com/makerdao/dockerized-auction-keeper/blob/master/flip/bat-a/flip-bat-a.sh#L18 from all flip-*-a.sh startup scripts

**Review by EdNoepel — CHANGES_REQUESTED** [review]
Upon review, I learned `dynamic_gas.sh` is also used to feed `dynamic_gas_params` to the `flip-[COLLATERAL].sh` startup script, so it cannot be deleted.

The old implemention used `GASPRICE_MULTIPLIER=1.6` for bidding only.  The keeper defaults to a less-aggresive --gas-initial-multiplier=1.0.  To maintain similar aggressiveness, we'd want to pass `--gas-initial-multiplier=1.6` in each of the `flip-[COLLATERAL].sh` startup scripts, perhaps by maintaining the `GASPRICE_MULTIPLIER` environment variable in `dynamic_gas.sh`.

**Review by EdNoepel — APPROVED** [review]
LGTM

**Review by grandizzy — APPROVED** [review]

**Comment by godsflaw** [comment]
@grandizzy do you have permissions to merge this?  If so, please do.

**Pull request merged**
